version: '3.8'

services:
  # API Gateway
  api_gateway:
    build: 
      context: ./api_gateway
    container_name: api_gateway
    ports:
      - "8000:8000"
    environment:
      - AUTH_SERVICE_URL=http://auth_service:8001
      - BOOK_SERVICE_URL=http://book_service:8002
      - CART_SERVICE_URL=http://cart_service:8003
    depends_on:
      - auth_service
      - book_service
      - cart_service
    networks:
      - bookshop_network

  # Auth Service
  auth_service:
    build: 
      context: ./auth_service
    container_name: auth_service
    ports:
      - "8001:8001"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/bookshop
      - BASE_URL=http://localhost:8000
      - jwtSecretKey=
      - JWT_ALGORITHM=HS256
      - smtpServer=smtp.gmail.com
      - smtpPort=587
      - senderEmail=
      - senderPassword=
    depends_on:
      - mongodb
    networks:
      - bookshop_network

  # Book Service
  book_service:
    build: 
      context: ./book_service
    container_name: book_service
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
      - MONGODB_URI=mongodb://mongodb:27017/bookshop
      - NODE_ENV=development
    volumes:
      - ./book_service/uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - bookshop_network

  # Cart Service
  cart_service:
    build: 
      context: ./cart_service
    container_name: cart_service
    ports:
      - "8003:8003"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/bookshop
      - BOOK_SERVICE_URL=http://book_service:8002
      - AUTH_SERVICE_URL=http://auth_service:8001
    depends_on:
      - mongodb
      - book_service
      - auth_service
    networks:
      - bookshop_network

  # Frontend Service

  # MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - bookshop_network
  
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - api_gateway
    networks:
      - bookshop_network

networks:
  bookshop_network:
    driver: bridge

volumes:
  mongodb_data: 